name: StaffChatBungee
main: me.vik1395.staffchatbungee.StaffChatBungeePlugin
version: ${project.version}
description: Custom version of StaffChatBungee. 4 streams of chat.
authors:
  - Vik1395
  - sarhatabaot